---

- name: Setup workstation.
  hosts: localhost

  vars_files:
    - defaults.yml

  tasks:
    - name: Install command line utilities.
      import_tasks: tasks/command-line-utilities.yml

    - name: Install GUI utilities.
      import_tasks: tasks/gui-utilities.yml

    - name: Setup configurations.
      import_tasks: tasks/configurations.yml
