---
# tasks file for ansible/command-line-utilities-work

- name: Include the necessary variables for work.
  include_vars: ../vars/command-line-utilities-work.yml
  tags:
    - work

- name: Add keys for work.
  apt_key:
    url: "{{ item.0 }}"
    state: present
    keyring: "{{ item.1 }}"
  with_together:
    - "{{ keys }}"
    - "{{ keys_paths }}"
  become: true

- name: Install repositories for work.
  apt_repository:
    repo: "{{ item.0 }}"
    filename: "{{ item.1 }}"
    state: present
    update_cache: yes
  with_together:
    - "{{ repositories }}"
    - "{{ repositories_names }}"
  become: true

- name: Install command line utilities for work.
  apt:
    name: '{{ command_line_utilities }}'
    state: latest
  become: true

#- name: Install binaries for work.
#  get_url:
#    url: "{{ item.0 }}"
#    dest: "/usr/local/bin/{{ item.1 }}"
#    force: yes
#    mode: 0755
#  with_together:
#    - "{{ binaries_url }}"
#    - "{{ binaries_name }}"
#  become: true
