---
# tasks file for roles/configurations-work

- name: Add my user to the correct groups for work.
  user:
    name: '{{ username }}'
    groups: '{{ local_groups }}'
    append: yes
    shell: '{{ shell }}'
  become: true

    #- name: Setup favorites in GNOME for work.
    #  dconf:
    #    key: "/org/gnome/shell/favorite-apps"
    #    value: "['org.gnome.Nautilus.desktop', 'firefox.desktop', 'fwbuilder.desktop', 'appimagekit-joplin.desktop', 'org.remmina.Remmina.desktop', 'spotify.desktop', 'thunderbird.desktop', 'com.gexperts.Tilix.desktop', 'virt-manager.desktop', 'code.desktop']"
    #    state: present
