---
# tasks file for roles/configurations-work

- name: Add my user to the correct groups for work.
  user:
    name: '{{ username }}'
    groups: '{{ local_groups }}'
    append: yes
    shell: '{{ shell }}'
  become: true
