---
# tasks file for roles/gui-utilities

- name: Add keys.
  apt_key:
    url: "{{ item.0 }}"
    state: present
    keyring: "{{ item.1 }}"
  with_together:
    - "{{ keys }}"
    - "{{ keys_paths }}"
  become: true

- name: Install repositories.
  apt_repository:
    repo: "{{ item.0 }}"
    filename: "{{ item.1 }}"
    state: present
    update_cache: yes
  with_together:
    - "{{ repositories }}"
    - "{{ repositories_names }}"
  become: true

- name: Install gui utilities.
  apt:
    name: '{{ gui_utilities }}'
    state: latest
  become: true

- name: Install downloaded debs.
  apt:
    deb: "{{ item }}"
  with_items: "{{ deb_urls }}"
  become: true
